---
abstract: 'A simple and fast interface to the bandcamp.com API'
author:
  - 'Hondallica <hondallica@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Bandcamp
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::Bandcamp:
    file: lib/WebService/Bandcamp.pm
    version: '0.05'
requires:
  Cache::LRU: '0'
  Carp: '0'
  Furl: '0'
  JSON::XS: '0'
  Moo: '0'
  Net::DNS::Lite: '0'
  URI: '0'
  URI::QueryParam: '0'
  namespace::clean: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/hondallica/p5-WebService-Bandcamp/issues
  homepage: https://github.com/hondallica/p5-WebService-Bandcamp
  repository: https://github.com/hondallica/p5-WebService-Bandcamp.git
version: '0.05'
